# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

# We can run multiple jobs in parallel. For this project
# I'm running Linux, Windows, and macOS jobs. For syntac details
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
jobs:

# Linux Job
- job: Linux

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    buildConfiguration: 'Release'

  steps:
  - script: dotnet restore
    displayName: 'dotnet restore'
  - script: dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'dotnet build $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*test/CookieManager.Test/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # MacOS Job
- job: MacOS

  pool:
    vmImage: 'macOS-latest'

  variables:
    buildConfiguration: 'Release'

  steps:
  - script: dotnet restore
    displayName: 'dotnet restore'
  - script: dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'dotnet build $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*test/CookieManager.Test/*.csproj'
      arguments: '--configuration $(buildConfiguration)'


    # Windos Job
- job: Windows

  pool:
    vmImage: 'windows-latest'

  variables:
    buildConfiguration: 'Release'

  steps:
  - script: dotnet restore
    displayName: 'dotnet restore'
  - script: dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'dotnet build $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*test/CookieManager.Test/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

